name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup environment
      run: |
        sudo apt-get update
        sudo apt-get install autotools-dev libltdl-dev libtool autoconf autopoint strace gawk
    - name: setup script
      run:  scripts/bootstrap.sh
    - name: configure
      run: ./configure --enable-debug 
    - name: make
      run: make
    - name: make check
      run: make check
    - name: check testlog
      run: cat ./test-suite.log
